# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
    config.vm.box = "tranphuquy19/centos7"
    config.vm.network "private_network", ip: "172.16.10.107"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.hostname = "jenkins.dora"
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = "jenkins.dora"
        vb.cpus = 2
        vb.memory = "2048"
    end
    
    config.vm.provision "shell", path: "./../install-docker-kube.sh"
    config.vm.provision "shell", path: "./../add-docker-user.sh"
    config.vm.provision "shell", path: "./../install-jenkins.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
        # Đặt pass 123 có tài khoản root và cho phép SSH
        echo "root@123" | passwd --stdin root
        sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
        systemctl reload sshd
        mkdir /home/app
        cd /home/app
        git clone https://github.com/tranphuquy19/nestjs-jenkins.git
        cd /home/app/nestjs-jenkins
        # yarn install --production && yarn build
        npm install && npm run build
        pm2 start ./dist/main.js
        SHELL
end