# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "tranphuquy19/centos7"
    config.vm.network "private_network", ip: "172.16.10.108"
    config.vm.hostname = "kube-master"
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = "kube.master"
        vb.cpus = 2
        vb.memory = "2048"
    end
    
    # config.vm.provision "shell", path: "./../install-docker-kube.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
echo "11231123" | passwd --stdin root
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd
cat >>/etc/hosts<<EOF
172.16.10.108 kube-master
172.16.10.109 kube-worker1
172.16.10.110 kube-worker2
EOF
SHELL
end
